services:
  database:
    container_name: postgres-dev
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
## Usar o Postgres-client (PSQL) para se conectar no banco de dados
# psql --host=localhost --username=postgres --port=5432
